/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Rupp;

import javax.swing.ImageIcon;

/**
 *
 * @author HAV
 */
public class ListName extends javax.swing.JFrame {

    /**
     * Creates new form ListName
     */
    public ListName() {
        initComponents();
    }
    public void clearData(){
        jcb1.setSelected(false);
        jcb2.setSelected(false);
        jcb3.setSelected(false);
        jcb4.setSelected(false);
        jcb5.setSelected(false);
        jcb6.setSelected(false);
        jcb7.setSelected(false);
        jcb8.setSelected(false);
        txtname.setText("");
        lbPhotos.setIcon(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngMemberName = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jcb8 = new javax.swing.JCheckBox();
        jcb1 = new javax.swing.JCheckBox();
        jcb2 = new javax.swing.JCheckBox();
        jcb3 = new javax.swing.JCheckBox();
        jcb4 = new javax.swing.JCheckBox();
        jcb5 = new javax.swing.JCheckBox();
        jcb6 = new javax.swing.JCheckBox();
        jcb7 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbPhotos = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1274, 716));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Khmer OS System", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("រូបថត");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, 130, 51));

        btngMemberName.add(jcb8);
        jcb8.setFont(new java.awt.Font("Khmer OS System", 1, 24)); // NOI18N
        jcb8.setForeground(new java.awt.Color(0, 255, 255));
        jcb8.setText("៨. អ៊ិត ជាហាវ");
        jcb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb8ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 180, 50));

        btngMemberName.add(jcb1);
        jcb1.setFont(new java.awt.Font("Khmer OS System", 1, 24)); // NOI18N
        jcb1.setForeground(new java.awt.Color(0, 255, 255));
        jcb1.setText("១. ឆៃ វិនូ");
        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 120, 50));

        btngMemberName.add(jcb2);
        jcb2.setFont(new java.awt.Font("Khmer OS System", 1, 24)); // NOI18N
        jcb2.setForeground(new java.awt.Color(0, 255, 255));
        jcb2.setText("២. សុខ វីវ៉ា");
        jcb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb2ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 150, 50));

        btngMemberName.add(jcb3);
        jcb3.setFont(new java.awt.Font("Khmer OS System", 1, 24)); // NOI18N
        jcb3.setForeground(new java.awt.Color(0, 255, 255));
        jcb3.setText("៣. សេន ហាំម៉ាត់");
        jcb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb3ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, 50));

        btngMemberName.add(jcb4);
        jcb4.setFont(new java.awt.Font("Khmer OS System", 1, 24)); // NOI18N
        jcb4.setForeground(new java.awt.Color(0, 255, 255));
        jcb4.setText("៤. ឃឿន ខេមរ៉ា");
        jcb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb4ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 200, 50));

        btngMemberName.add(jcb5);
        jcb5.setFont(new java.awt.Font("Khmer OS System", 1, 24)); // NOI18N
        jcb5.setForeground(new java.awt.Color(0, 255, 255));
        jcb5.setText("៥.​ជា ណារ៉ុង");
        jcb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb5ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 170, 50));

        btngMemberName.add(jcb6);
        jcb6.setFont(new java.awt.Font("Khmer OS System", 1, 24)); // NOI18N
        jcb6.setForeground(new java.awt.Color(0, 255, 255));
        jcb6.setText("៦. ឆុន នរបតី");
        jcb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb6ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 170, 50));

        btngMemberName.add(jcb7);
        jcb7.setFont(new java.awt.Font("Khmer OS System", 1, 24)); // NOI18N
        jcb7.setForeground(new java.awt.Color(0, 255, 255));
        jcb7.setText("៧. អឿន សំអុល");
        jcb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb7ActionPerformed(evt);
            }
        });
        getContentPane().add(jcb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 210, 50));

        jLabel2.setFont(new java.awt.Font("Khmer OS System", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("សាកលវិទ្យាល័យ ភូមិន្ទភ្នំពេញ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1270, 60));

        jLabel3.setFont(new java.awt.Font("Khmer OS System", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ឈ្មោះ សមាជិកក្រុម");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 300, 51));

        jLabel4.setFont(new java.awt.Font("Khmer OS System", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ឈ្មោះ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 130, 51));

        lbPhotos.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        lbPhotos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(lbPhotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 420, 530));

        btnClear.setBackground(new java.awt.Color(0, 102, 102));
        btnClear.setFont(new java.awt.Font("Khmer OS System", 1, 24)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rupp/Photos/clear.png"))); // NOI18N
        btnClear.setText("សម្អាត");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, 160, 50));

        txtname.setBackground(new java.awt.Color(102, 102, 102));
        txtname.setFont(new java.awt.Font("Khmer OS System", 1, 36)); // NOI18N
        txtname.setForeground(new java.awt.Color(51, 255, 255));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 340, 70));

        btnExit.setBackground(new java.awt.Color(0, 102, 102));
        btnExit.setFont(new java.awt.Font("Khmer OS System", 1, 24)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rupp/Photos/close.png"))); // NOI18N
        btnExit.setText("ចាកចេញ");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, 200, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rupp/Photos/name.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb2ActionPerformed
        // TODO add your handling code here:
        String photos = "E:\\Image\\viva.jpg";
        String Name = "២. សុខ វីវ៉ា";
        if(jcb2.isSelected()){
            txtname.setText(Name);
            lbPhotos.setIcon(new ImageIcon(photos)); 
        }
        else{
            txtname.setText("");
            lbPhotos.setIcon(null);
        }
    }//GEN-LAST:event_jcb2ActionPerformed

    private void jcb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb8ActionPerformed
        // TODO add your handling code here:
        String photos = "E:\\Image\\ha.jpg";
        String Name = "៨. អ៊ិត ជាហាវ";
        if(jcb8.isSelected()){
            txtname.setText(Name);
            lbPhotos.setIcon(new ImageIcon(photos)); 
        }
        else{
            txtname.setText("");
            lbPhotos.setIcon(null);
        }
    }//GEN-LAST:event_jcb8ActionPerformed

    private void jcb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb7ActionPerformed
        // TODO add your handling code here:
        String photos = "E:\\Image\\ol.jpg";
        String Name = "៧. អឿន សំអុល";
        if(jcb7.isSelected()){
            txtname.setText(Name);
            lbPhotos.setIcon(new ImageIcon(photos));  
        }
        else{
            txtname.setText("");
            lbPhotos.setIcon(null);
        }
    }//GEN-LAST:event_jcb7ActionPerformed

    private void jcb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb6ActionPerformed
        // TODO add your handling code here:
        String photos = "E:\\Image\\votey.jpg";
        String Name = "៦. ឆុន នរបតី";
        if(jcb6.isSelected()){
            txtname.setText(Name);
            lbPhotos.setIcon(new ImageIcon(photos));
        }
        else{
            txtname.setText("");
            lbPhotos.setIcon(null);
        }
    }//GEN-LAST:event_jcb6ActionPerformed

    private void jcb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb3ActionPerformed
        // TODO add your handling code here:
        String photos = "E:\\Image\\hamat.jpg";
        String Name = "៣. សេន ហាំម៉ាត់";
        if(jcb3.isSelected()){
            txtname.setText(Name);
            lbPhotos.setIcon(new ImageIcon(photos));
        }
        else{
            txtname.setText("");
            lbPhotos.setIcon(null);
        }
    }//GEN-LAST:event_jcb3ActionPerformed

    private void jcb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb4ActionPerformed
        // TODO add your handling code here:
        String photos = "E:\\Image\\khamara.jpg";
        String Name = "៤. ឃឿន ខេមរ៉ា";
        if(jcb4.isSelected()){
            txtname.setText(Name);
            lbPhotos.setIcon(new ImageIcon(photos));
        }
        else{
            txtname.setText("");
            lbPhotos.setIcon(null);
        }
    }//GEN-LAST:event_jcb4ActionPerformed

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
        // TODO add your handling code here:
        String photos = "E:\\Image\\vinou.jpg";
        String Name = "១. ឆៃ វិនូ";
        if(jcb1.isSelected()){
            txtname.setText(Name);
            lbPhotos.setIcon(new ImageIcon(photos));
        }
        else{
            txtname.setText("");
            lbPhotos.setIcon(null);
        }
    }//GEN-LAST:event_jcb1ActionPerformed

    private void jcb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb5ActionPerformed
        // TODO add your handling code here:
        String photos = "E:\\Image\\narong.jpg";
        String Name = "៥.​ជា ណារ៉ុង";
        if(jcb5.isSelected()){
            txtname.setText(Name);
            lbPhotos.setIcon(new ImageIcon(photos));
        }
        else{
            txtname.setText("");
            lbPhotos.setIcon(null);
        }
    }//GEN-LAST:event_jcb5ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btngMemberName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox jcb1;
    private javax.swing.JCheckBox jcb2;
    private javax.swing.JCheckBox jcb3;
    private javax.swing.JCheckBox jcb4;
    private javax.swing.JCheckBox jcb5;
    private javax.swing.JCheckBox jcb6;
    private javax.swing.JCheckBox jcb7;
    private javax.swing.JCheckBox jcb8;
    private javax.swing.JLabel lbPhotos;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
