package Form;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Balance extends javax.swing.JFrame {

    /**
     * Creates new form Balance
     */
    public Balance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(385, 480));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SN KH KAMPONG CHAM", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("DEPOSIT AND WITHDRAW");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 20, 200, 30);

        jToggleButton3.setBackground(new java.awt.Color(102, 153, 255));
        jToggleButton3.setText("Back");
        jPanel2.add(jToggleButton3);
        jToggleButton3.setBounds(10, 10, 60, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 370, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 60);

        jLabel3.setBackground(new java.awt.Color(102, 102, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("DEPOSIT AND WITHDRAW METHODS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 210, 270, 30);

        jLabel4.setText("customer support team available 24/7 via live chat, email, or phone.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 320, 370, 16);

        jLabel5.setText("~Maximum withdrawal amount per transaction: $5,000.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 300, 16);

        jLabel6.setBackground(new java.awt.Color(102, 102, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("DEPOSITE RULE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 130, 30);

        jLabel7.setText("~ Minimum deposit amount: $10");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 100, 190, 16);

        jLabel8.setText("~Maximum deposit amount per transaction: $10,000.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 120, 280, 16);

        jLabel9.setBackground(new java.awt.Color(102, 102, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Customer Support");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 270, 130, 30);

        jLabel10.setText("~Credit/Debit Card");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 260, 210, 16);

        jLabel11.setText("~Minimum withdrawal amount: $20");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 170, 210, 16);

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 153));
        jToggleButton1.setText("WITHDRAW");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(260, 400, 93, 30);

        jToggleButton2.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton2.setText("DEPOSITE");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(260, 360, 90, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 380, 210, 30);

        jLabel12.setBackground(new java.awt.Color(102, 102, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("WITHDRAW RULE");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 140, 130, 30);

        jLabel13.setText("~Bank Transfer");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 240, 210, 16);

        jLabel14.setText("       For any issues or queries regarding withdrawals, contact our");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 300, 340, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piggy-bank-finance-background-diy-dry-clay-creative-art-kids.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 60, 370, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Form_2 f2=new Form_2();
        f2.show();
        dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Balance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
