package Form;


import java.awt.Color;
import java.io.File;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author USER
 */
public class DiceGame extends javax.swing.JFrame {

    /**
     * Creates new form DiceGame
     */
    public DiceGame() {
        initComponents();
        win_label.setText("0");
        lose_label.setText("0");
        draw_label.setText("0");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dice2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dice1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        roll_btn = new javax.swing.JToggleButton();
        result = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        win_label = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lose_label = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        draw_label = new javax.swing.JLabel();
        restart_btn = new javax.swing.JToggleButton();
        back = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("D I C E   G A M E");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 20, 1000, 60);

        dice2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/photo/dice1.png"))); // NOI18N
        jPanel1.add(dice2);
        dice2.setBounds(320, 160, 210, 210);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RULE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 320, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel2.setText("  admin, it means you win the game.");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 80, 290, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("How to play");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 220, 280, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel9.setText("- If your dice number is bigger than an ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 50, 290, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel10.setText("- If your dice number is smaller than an ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 130, 300, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel11.setText("  admin, it means you lose the game.");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 160, 290, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel12.setText("- Click Roll Button");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 270, 280, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(640, 130, 320, 340);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(null);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RULE");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 10, 320, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(640, 130, 320, 320);

        dice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/photo/dice1.png"))); // NOI18N
        jPanel1.add(dice1);
        dice1.setBounds(50, 160, 210, 210);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Computer");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 400, 120, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Player");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 400, 80, 40);

        roll_btn.setBackground(new java.awt.Color(204, 204, 204));
        roll_btn.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        roll_btn.setText(" Roll");
        roll_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roll_btnActionPerformed(evt);
            }
        });
        jPanel1.add(roll_btn);
        roll_btn.setBounds(30, 470, 150, 60);
        jPanel1.add(result);
        result.setBounds(250, 470, 220, 60);

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel17.setText("Win :");
        jLabel17.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel17HierarchyChanged(evt);
            }
        });
        jPanel1.add(jLabel17);
        jLabel17.setBounds(40, 560, 50, 30);

        win_label.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jPanel1.add(win_label);
        win_label.setBounds(100, 560, 60, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel18.setText("Lose :");
        jLabel18.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel18HierarchyChanged(evt);
            }
        });
        jPanel1.add(jLabel18);
        jLabel18.setBounds(170, 560, 70, 30);

        lose_label.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jPanel1.add(lose_label);
        lose_label.setBounds(240, 560, 60, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel19.setText("Tie :");
        jLabel19.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel19HierarchyChanged(evt);
            }
        });
        jPanel1.add(jLabel19);
        jLabel19.setBounds(340, 560, 70, 30);

        draw_label.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jPanel1.add(draw_label);
        draw_label.setBounds(390, 560, 60, 30);

        restart_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        restart_btn.setText("Restart");
        restart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restart_btnActionPerformed(evt);
            }
        });
        jPanel1.add(restart_btn);
        restart_btn.setBounds(490, 550, 120, 40);

        back.setBackground(new java.awt.Color(102, 204, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(10, 10, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

int win=1;
int lose=1;
int draw=1;
    private void roll_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roll_btnActionPerformed
        roll_btn.setEnabled(false);
        Random random = new Random();

        Thread th = new Thread() {
            int num1, num2;

            @Override
            public void run() {
                for (int i = 0; i < 20; i++) {

                    int diceValue1 = random.nextInt(6) + 1;
                    num1 = diceValue1;
                    String diceFile = "/Form/photo/dice" + diceValue1 + ".png";

                    dice1.setIcon(new ImageIcon(getClass().getResource(diceFile)));

                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                }
                for (int i = 0; i < 20; i++) {
                    int diceValue2 = random.nextInt(6) + 1;
                    num2 = diceValue2;
                    String diceFile1 = "/Form/photo/dice" + diceValue2 + ".png";

                    dice2.setIcon(new ImageIcon(getClass().getResource(diceFile1)));
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
                if (num1 > num2) {
                    result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/win.png")));
                    win_label.setText(""+win+++"");
                } else if (num1 < num2) {
                    result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/lose.png")));
                    lose_label.setText(""+lose+++"");
                } else {
                    result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/draw.png")));
                    draw_label.setText(""+draw+++"");
                }
                roll_btn.setEnabled(true);
            }
        };

        th.start();

    }//GEN-LAST:event_roll_btnActionPerformed

    private void jLabel17HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel17HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17HierarchyChanged

    private void jLabel18HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel18HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18HierarchyChanged

    private void jLabel19HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel19HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19HierarchyChanged

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Form_2 f2 = new Form_2();
        f2.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void restart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restart_btnActionPerformed
        win_label.setText("0");
        lose_label.setText("0");
        result.setIcon(null);
        draw_label.setText("0");
        dice1.setIcon(new ImageIcon(getClass().getResource("/Form/photo/dice1.png")));
        dice2.setIcon(new ImageIcon(getClass().getResource("/Form/photo/dice1.png")));
    }//GEN-LAST:event_restart_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton back;
    private javax.swing.JLabel dice1;
    private javax.swing.JLabel dice2;
    private javax.swing.JLabel draw_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lose_label;
    private javax.swing.JToggleButton restart_btn;
    private javax.swing.JLabel result;
    private javax.swing.JToggleButton roll_btn;
    private javax.swing.JLabel win_label;
    // End of variables declaration//GEN-END:variables
}
