package Form;


import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author USER
 */
public class Lottery extends javax.swing.JFrame {

    /**
     * Creates new form Lottery
     */
    public Lottery() {
        initComponents();
        win_label.setText("0");
        lose_label.setText("0");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton6 = new javax.swing.JToggleButton();
        jTextField6 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        spin_btn = new javax.swing.JToggleButton();
        lottery_txt = new javax.swing.JTextField();
        first = new javax.swing.JTextField();
        result = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        win_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lose_label = new javax.swing.JLabel();
        restart_btn = new javax.swing.JToggleButton();

        jToggleButton6.setBackground(new java.awt.Color(102, 204, 255));
        jToggleButton6.setText("Back");

        jToggleButton2.setBackground(new java.awt.Color(51, 255, 0));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("L O T T E R Y");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 20, 1000, 60);

        back.setBackground(new java.awt.Color(102, 204, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(10, 10, 80, 30);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RULE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 320, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("random again.");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 320, 260, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("How to play");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 170, 280, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel12.setText("- Click Roll Button");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 250, 280, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel13.setText("a random number, you win the game.");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 120, 290, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel14.setText("- Place your bet inside the Text Field");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 220, 280, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("Note: The Number already random can be");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(0, 290, 320, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel19.setText("- Lottery Number Start From 1 to 10");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 40, 280, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel20.setText("- If you the number you input match to ");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 80, 290, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(620, 130, 320, 390);

        spin_btn.setBackground(new java.awt.Color(204, 255, 204));
        spin_btn.setFont(new java.awt.Font("Segoe UI Black", 3, 30)); // NOI18N
        spin_btn.setText("SPIN");
        spin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spin_btnActionPerformed(evt);
            }
        });
        jPanel1.add(spin_btn);
        spin_btn.setBounds(20, 360, 150, 50);

        lottery_txt.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lottery_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottery_txtActionPerformed(evt);
            }
        });
        jPanel1.add(lottery_txt);
        lottery_txt.setBounds(240, 360, 330, 50);

        first.setFont(new java.awt.Font("Segoe UI Black", 1, 90)); // NOI18N
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });
        jPanel1.add(first);
        first.setBounds(240, 130, 330, 180);
        jPanel1.add(result);
        result.setBounds(70, 190, 190, 60);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel4.setText("Win :");
        jLabel4.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel4HierarchyChanged(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 470, 50, 30);

        win_label.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jPanel1.add(win_label);
        win_label.setBounds(90, 470, 60, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel7.setText("Lose :");
        jLabel7.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel7HierarchyChanged(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 470, 70, 30);

        lose_label.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jPanel1.add(lose_label);
        lose_label.setBounds(300, 470, 60, 30);

        restart_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        restart_btn.setText("Restart");
        restart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restart_btnActionPerformed(evt);
            }
        });
        jPanel1.add(restart_btn);
        restart_btn.setBounds(450, 460, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Balance b = new Balance();
        b.show();
        dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed
int win=1;
int lose=1;

    private void spin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spin_btnActionPerformed

        Random random = new Random();
        
        Thread thread = new Thread(() -> {
            int num = 0;
            
            try {
                if (Integer.parseInt(lottery_txt.getText()) > 0 && Integer.parseInt(lottery_txt.getText()) <= 10) {
                    for (int i = 0; i < 15; i++) {
                        int num1 = random.nextInt(10) + 1;
                        num = num1;
                        first.setHorizontalAlignment(JTextField.CENTER);
                        first.setText(Integer.toString(num1));
                        Thread.sleep(10); // Introduce a small delay
                    }

                    int lot = Integer.parseInt(lottery_txt.getText().trim());

                    if (num == lot) {
                        result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/win.png")));
                        win_label.setText(""+win+++"");
                    } else {
                        result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/lose.png")));
                        lose_label.setText(""+lose+++"");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Number must be between 1 and 10");
                    lottery_txt.setText("");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter a valid number");
                lottery_txt.setText("");
            } catch (InterruptedException e) {
                e.printStackTrace(); // Handle interrupted exception
            }
        });

        thread.start(); // Start the thread

    }//GEN-LAST:event_spin_btnActionPerformed

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Form_2 f2 = new Form_2();
        f2.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jLabel4HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel4HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4HierarchyChanged

    private void jLabel7HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel7HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7HierarchyChanged

    private void lottery_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottery_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lottery_txtActionPerformed

    private void restart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restart_btnActionPerformed
        // TODO add your handling code here:
        lottery_txt.setText("");
        win_label.setText("0");
        lose_label.setText("0");
        result.setIcon(null);
        first.setText("");
    }//GEN-LAST:event_restart_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lottery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lottery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lottery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lottery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lottery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton back;
    private javax.swing.JTextField first;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JLabel lose_label;
    private javax.swing.JTextField lottery_txt;
    private javax.swing.JToggleButton restart_btn;
    private javax.swing.JLabel result;
    private javax.swing.JToggleButton spin_btn;
    private javax.swing.JLabel win_label;
    // End of variables declaration//GEN-END:variables
}
