package Form;


import java.util.Random;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author USER
 */
public class RPS extends javax.swing.JFrame {

    /**
     * Creates new form RPS
     */
    public RPS() {
        initComponents();
        win_label.setText("0");
        lose_label.setText("0");
        draw_label.setText("0");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rps_lab = new javax.swing.JLabel();
        scissor_btn = new javax.swing.JToggleButton();
        paper_btn = new javax.swing.JToggleButton();
        rock_btn = new javax.swing.JToggleButton();
        result = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rps_label1 = new javax.swing.JLabel();
        win_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lose_label = new javax.swing.JLabel();
        restart_btn = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        draw_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROCK PAPER SCISSORS  G A M E");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 20, 1000, 60);

        back.setBackground(new java.awt.Color(102, 204, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(10, 10, 70, 30);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RULE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 320, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel2.setText("- Rock > Scissor");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 70, 290, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("How to play");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 160, 280, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel9.setText("- Paper > Rock ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 40, 290, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel10.setText("- Scissor > Paper");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 100, 300, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel12.setText("- click stop to stop the random ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 230, 280, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel14.setText("- choose Rock Paper Or Scissor ");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 200, 280, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(640, 130, 320, 300);

        rps_lab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/photo/rock_paper.png"))); // NOI18N
        jPanel1.add(rps_lab);
        rps_lab.setBounds(20, 160, 210, 210);

        scissor_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/photo/scissor.png"))); // NOI18N
        scissor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissor_btnActionPerformed(evt);
            }
        });
        jPanel1.add(scissor_btn);
        scissor_btn.setBounds(220, 390, 130, 130);

        paper_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/photo/rock.png"))); // NOI18N
        paper_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paper_btnActionPerformed(evt);
            }
        });
        jPanel1.add(paper_btn);
        paper_btn.setBounds(20, 390, 130, 130);

        rock_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/photo/paper.png"))); // NOI18N
        rock_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rock_btnActionPerformed(evt);
            }
        });
        jPanel1.add(rock_btn);
        rock_btn.setBounds(420, 390, 130, 130);
        jPanel1.add(result);
        result.setBounds(250, 180, 120, 60);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel4.setText("Win :");
        jLabel4.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel4HierarchyChanged(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 550, 50, 20);

        rps_label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form/photo/rock_paper.png"))); // NOI18N
        jPanel1.add(rps_label1);
        rps_label1.setBounds(400, 150, 210, 210);

        win_label.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jPanel1.add(win_label);
        win_label.setBounds(100, 550, 60, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel7.setText("Lose :");
        jLabel7.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel7HierarchyChanged(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 550, 70, 20);

        lose_label.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jPanel1.add(lose_label);
        lose_label.setBounds(230, 550, 60, 20);

        restart_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        restart_btn.setForeground(new java.awt.Color(102, 255, 51));
        restart_btn.setText("Restart");
        restart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restart_btnActionPerformed(evt);
            }
        });
        jPanel1.add(restart_btn);
        restart_btn.setBounds(470, 530, 120, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel11.setText("Tie :");
        jLabel11.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel11HierarchyChanged(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(310, 550, 70, 20);

        draw_label.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jPanel1.add(draw_label);
        draw_label.setBounds(370, 550, 60, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setText("Computer");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 90, 130, 33);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setText("You");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 90, 60, 33);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Form_2 f2 = new Form_2();
        f2.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed
    int win = 1;
    int lose = 1;
    int draw = 1;
    private void paper_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paper_btnActionPerformed
        rps_lab.setIcon(new ImageIcon(getClass().getResource("/Form/photo/rps1.png")));
        Random random = new Random();
        String paper = "/Form/photo/rps1.png";  // Paper
        String rock = "/Form/photo/rps2.png";   // Rock
        String scissor = "/Form/photo/rps3.png"; // Scissors
        int Value1 = random.nextInt(3) + 1;
        String File = "/Form/photo/rps" + Value1 + ".png";
        rps_label1.setIcon(new ImageIcon(getClass().getResource(File)));

        // The result should be checked outside the loop to avoid frequent UI updates.
        if (paper.equalsIgnoreCase(File)) {
            result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/draw.png")));
            draw_label.setText("" + draw++ + "");
        } else if (rock.equalsIgnoreCase(File)) {
            result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/win.png")));
            win_label.setText("" + win++ + "");
        } else {
            result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/lose.png")));
            lose_label.setText("" + lose++ + "");
        }
        paper_btn.setSelected(false);
    }//GEN-LAST:event_paper_btnActionPerformed

    private void scissor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissor_btnActionPerformed
        rps_lab.setIcon(new ImageIcon(getClass().getResource("/Form/photo/rps3.png")));
        Random random = new Random();
        String paper = "/Form/photo/rps1.png";  // Paper
        String rock = "/Form/photo/rps2.png";   // Rock
        String scissor = "/Form/photo/rps3.png"; // Scissors
        int Value1 = random.nextInt(3) + 1;
        String File = "/Form/photo/rps" + Value1 + ".png";
        rps_label1.setIcon(new ImageIcon(getClass().getResource(File)));

        // The result should be checked outside the loop to avoid frequent UI updates.
        if (scissor.equalsIgnoreCase(File)) {
            result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/draw.png")));
            draw_label.setText("" + draw++ + "");
        } else if (paper.equalsIgnoreCase(File)) {
            result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/win.png")));

            win_label.setText("" + win++ + "");
        } else {
            result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/lose.png")));
            lose_label.setText("" + lose++ + "");
        }
        scissor_btn.setSelected(false);
    }//GEN-LAST:event_scissor_btnActionPerformed

    private void rock_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rock_btnActionPerformed
        // TODO add your handling code here:
        rps_lab.setIcon(new ImageIcon(getClass().getResource("/Form/photo/rps2.png")));
        Random random = new Random();
        String paper = "/Form/photo/rps1.png";  // Paper
        String rock = "/Form/photo/rps2.png";   // Rock
        String scissor = "/Form/photo/rps3.png"; // Scissors
        int Value1 = random.nextInt(3) + 1;
        String File = "/Form/photo/rps" + Value1 + ".png";
        rps_label1.setIcon(new ImageIcon(getClass().getResource(File)));

        // The result should be checked outside the loop to avoid frequent UI updates.
        if (rock.equalsIgnoreCase(File)) {
            result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/draw.png")));
            draw_label.setText("" + draw++ + "");
        } else if (scissor.equalsIgnoreCase(File)) {
            result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/win.png")));
            win_label.setText("" + win++ + "");
        } else {
            result.setIcon(new ImageIcon(getClass().getResource("/Form/photo/lose.png")));
            lose_label.setText("" + lose++ + "");
        }
        rock_btn.setSelected(false);
    }//GEN-LAST:event_rock_btnActionPerformed

    private void jLabel4HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel4HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4HierarchyChanged

    private void jLabel7HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel7HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7HierarchyChanged

    private void jLabel11HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel11HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11HierarchyChanged

    private void restart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restart_btnActionPerformed
        // TODO add your handling code here:
        win_label.setText("0");
        lose_label.setText("0");
        rps_label1.setIcon(new ImageIcon(getClass().getResource("/Form/photo/rock_paper.png")));
        rps_lab.setIcon(new ImageIcon(getClass().getResource("/Form/photo/rock_paper.png")));
        draw_label.setText("0");
        result.setIcon(null);
    }//GEN-LAST:event_restart_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton back;
    private javax.swing.JLabel draw_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lose_label;
    private javax.swing.JToggleButton paper_btn;
    private javax.swing.JToggleButton restart_btn;
    private javax.swing.JLabel result;
    private javax.swing.JToggleButton rock_btn;
    private javax.swing.JLabel rps_lab;
    private javax.swing.JLabel rps_label1;
    private javax.swing.JToggleButton scissor_btn;
    private javax.swing.JLabel win_label;
    // End of variables declaration//GEN-END:variables
}
